---
language: generic
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - name: build
      language: nix
      script: nix-build
    - stage: deploy
      name: deploy
      language: nix
      script: ./channel-build _output
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: "FOOO"
        local_dir: _output
        target-branch: gh-pages
        on:
          branch: master
