---
language: generic
stages:
  - test
  - name: deploy
    if: branch = publish
jobs:
  include:
    - stage: test
      name: omnilint
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
    - name: build
      language: nix
      script: nix-build
